buildscript {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'org.graphoenix:graphoenix-gradle-plugin:0.1.0-SNAPSHOT'
    }
}

plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.5'
}

apply plugin: 'io.graphoenix'

classes {
    dependsOn generateGraphQLSource
    dependsOn generateProtobufV3
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.8'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.73.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/java'
            srcDirs 'build/generated/source/proto/main/grpc'
        }
    }
}

group = 'demo.gp.review'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation platform('org.graphoenix:graphoenix-platform:0.1.0-SNAPSHOT')

    implementation project(':user-package')
    implementation 'org.graphoenix:graphoenix-core'
    implementation 'org.graphoenix:nozdormu-inject'
    implementation 'org.graphoenix:nozdormu-async'
    implementation 'org.graphoenix:nozdormu-interceptor'
    implementation 'org.graphoenix:nozdormu-config'

    runtimeOnly 'io.grpc:grpc-netty-shaded'
    implementation 'io.grpc:grpc-protobuf'
    implementation 'io.grpc:grpc-stub'
    compileOnly 'org.apache.tomcat:annotations-api' // necessary for Java 9+

    annotationProcessor platform('org.graphoenix:graphoenix-platform:0.1.0-SNAPSHOT')
    annotationProcessor project(':user-package')
    annotationProcessor 'org.graphoenix:graphoenix-annotation-processor'
    annotationProcessor 'org.graphoenix:nozdormu-inject'
    annotationProcessor 'org.graphoenix:nozdormu-async'
    annotationProcessor 'org.graphoenix:nozdormu-interceptor'
    annotationProcessor 'org.graphoenix:nozdormu-config'

    protobuf platform('org.graphoenix:graphoenix-platform:0.1.0-SNAPSHOT')
    protobuf 'org.graphoenix:graphoenix-core'
    protobuf project(':user-package')

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}