"产品"
type Product {
    "产品ID"
    id: ID
    "产品名称"
    name: String!
    "定价"
    price: Float!
    "评论列表"
    reviews: [Review!]
}

"订单"
type Order {
    "订单ID"
    id: ID
    "购买用户"
    user: User!
    "产品列表"
    items: [OrderItem!]!
}

"订单项"
type OrderItem {
    "订单项ID"
    id: ID
    "产品"
    product: Product!
    "购买数量"
    quantity: Int!
}
