syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.order.dto.objectType.grpc";

package demo.gp.order;

import "demo/gp/order/enums.proto";
import "demo/gp/review/objects.proto";
import "demo/gp/user/objects.proto";
import "io/graphoenix/core/objects.proto";
import "google/protobuf/timestamp.proto";

/**
* 产品
*/
message Product {
    string id = 1; /* 产品ID */
    optional string name = 2; /* 产品名称 */
    optional float price = 3; /* 定价 */
    repeated demo.gp.review.Review reviews = 4; /* 评论列表 */
    bool is_deprecated = 5; /* Is Deprecated */
    int32 version = 6; /* Version */
    int32 realm_id = 7; /* Realm ID */
    string create_user_id = 8; /* Create User ID */
    google.protobuf.Timestamp create_time = 9; /* Create Time */
    string update_user_id = 10; /* Update User ID */
    google.protobuf.Timestamp update_time = 11; /* Update Time */
    string create_group_id = 12; /* Create Group ID */
    string intro_typename = 13; /* Type Name */
    repeated ProductReviewRelation product_review_relation = 14; /* Relationship Object between 产品 and 评论 */
    int32 id_count = 15; /* Count of 产品 */
    int32 id_max = 16; /* Max of 产品ID */
    int32 id_min = 17; /* Min of 产品ID */
    int32 name_count = 18; /* Count of 产品名称 */
    string name_max = 19; /* Max of 产品名称 */
    string name_min = 20; /* Min of 产品名称 */
    int32 price_count = 21; /* Count of 定价 */
    float price_sum = 22; /* Sum of 定价 */
    float price_avg = 23; /* Avg of 定价 */
    float price_max = 24; /* Max of 定价 */
    float price_min = 25; /* Min of 定价 */
}
/**
* 订单
*/
message Order {
    string id = 1; /* 订单ID */
    optional demo.gp.user.User user = 2; /* 购买用户 */
    repeated OrderItem items = 3; /* 产品列表 */
    bool is_deprecated = 4; /* Is Deprecated */
    int32 version = 5; /* Version */
    int32 realm_id = 6; /* Realm ID */
    string create_user_id = 7; /* Create User ID */
    google.protobuf.Timestamp create_time = 8; /* Create Time */
    string update_user_id = 9; /* Update User ID */
    google.protobuf.Timestamp update_time = 10; /* Update Time */
    string create_group_id = 11; /* Create Group ID */
    string intro_typename = 12; /* Type Name */
    repeated OrderUserRelation order_user_relation = 13; /* Relationship Object between 订单 and 用户 */
    repeated OrderOrderItemRelation order_order_item_relation = 14; /* Relationship Object between 订单 and 订单项 */
    OrderItem items_aggregate = 15; /* Aggregate Field for 产品列表 */
    OrderItemConnection items_connection = 16; /* Connection Field for 产品列表 */
    OrderOrderItemRelation order_order_item_relation_aggregate = 17; /* Aggregate Field for Relationship Object between 订单 and 订单项 */
    OrderOrderItemRelationConnection order_order_item_relation_connection = 18; /* Connection Field for Relationship Object between 订单 and 订单项 */
    int32 id_count = 19; /* Count of 订单 */
    int32 id_max = 20; /* Max of 订单ID */
    int32 id_min = 21; /* Min of 订单ID */
    float total = 22;
}
/**
* 订单项
*/
message OrderItem {
    string id = 1; /* 订单项ID */
    optional Product product = 2; /* 产品 */
    optional int32 quantity = 3; /* 购买数量 */
    bool is_deprecated = 4; /* Is Deprecated */
    int32 version = 5; /* Version */
    int32 realm_id = 6; /* Realm ID */
    string create_user_id = 7; /* Create User ID */
    google.protobuf.Timestamp create_time = 8; /* Create Time */
    string update_user_id = 9; /* Update User ID */
    google.protobuf.Timestamp update_time = 10; /* Update Time */
    string create_group_id = 11; /* Create Group ID */
    string intro_typename = 12; /* Type Name */
    repeated OrderItemProductRelation order_item_product_relation = 13; /* Relationship Object between 订单项 and 产品 */
    OrderItemProductRelation order_item_product_relation_aggregate = 14; /* Aggregate Field for Relationship Object between 订单项 and 产品 */
    OrderItemProductRelationConnection order_item_product_relation_connection = 15; /* Connection Field for Relationship Object between 订单项 and 产品 */
    int32 id_count = 16; /* Count of 订单项 */
    int32 id_max = 17; /* Max of 订单项ID */
    int32 id_min = 18; /* Min of 订单项ID */
    int32 quantity_count = 19; /* Count of 购买数量 */
    int32 quantity_sum = 20; /* Sum of 购买数量 */
    int32 quantity_avg = 21; /* Avg of 购买数量 */
    int32 quantity_max = 22; /* Max of 购买数量 */
    int32 quantity_min = 23; /* Min of 购买数量 */
}
/**
* Relationship Object between 订单 and 订单项
*/
message OrderOrderItemRelation {
    string id = 1; /* ID */
    string order_ref = 2; /* 订单 Reference */
    Order order = 3; /* 订单 */
    string order_item_ref = 4; /* 订单项 Reference */
    OrderItem order_item = 5; /* 订单项 */
    bool is_deprecated = 6; /* Is Deprecated */
    int32 version = 7; /* Version */
    int32 realm_id = 8; /* Realm ID */
    string create_user_id = 9; /* Create User ID */
    google.protobuf.Timestamp create_time = 10; /* Create Time */
    string update_user_id = 11; /* Update User ID */
    google.protobuf.Timestamp update_time = 12; /* Update Time */
    string create_group_id = 13; /* Create Group ID */
    string intro_typename = 14; /* Type Name */
    int32 id_count = 15; /* Count of Relationship Object between 订单 and 订单项 */
    int32 id_max = 16; /* Max of ID */
    int32 id_min = 17; /* Min of ID */
    int32 order_ref_count = 18; /* Count of 订单 Reference */
    string order_ref_max = 19; /* Max of 订单 Reference */
    string order_ref_min = 20; /* Min of 订单 Reference */
    int32 order_item_ref_count = 21; /* Count of 订单项 Reference */
    string order_item_ref_max = 22; /* Max of 订单项 Reference */
    string order_item_ref_min = 23; /* Min of 订单项 Reference */
}
/**
* Relationship Object between 订单项 and 产品
*/
message OrderItemProductRelation {
    string id = 1; /* ID */
    string order_item_ref = 2; /* 订单项 Reference */
    OrderItem order_item = 3; /* 订单项 */
    string product_ref = 4; /* 产品 Reference */
    Product product = 5; /* 产品 */
    bool is_deprecated = 6; /* Is Deprecated */
    int32 version = 7; /* Version */
    int32 realm_id = 8; /* Realm ID */
    string create_user_id = 9; /* Create User ID */
    google.protobuf.Timestamp create_time = 10; /* Create Time */
    string update_user_id = 11; /* Update User ID */
    google.protobuf.Timestamp update_time = 12; /* Update Time */
    string create_group_id = 13; /* Create Group ID */
    string intro_typename = 14; /* Type Name */
    int32 id_count = 15; /* Count of Relationship Object between 订单项 and 产品 */
    int32 id_max = 16; /* Max of ID */
    int32 id_min = 17; /* Min of ID */
    int32 order_item_ref_count = 18; /* Count of 订单项 Reference */
    string order_item_ref_max = 19; /* Max of 订单项 Reference */
    string order_item_ref_min = 20; /* Min of 订单项 Reference */
    int32 product_ref_count = 21; /* Count of 产品 Reference */
    string product_ref_max = 22; /* Max of 产品 Reference */
    string product_ref_min = 23; /* Min of 产品 Reference */
}
/**
* Relationship Object between 产品 and 评论
*/
message ProductReviewRelation {
    string id = 1; /* ID */
    string product_ref = 2; /* 产品 Reference */
    Product product = 3; /* 产品 */
    int32 review_ref = 4; /* 评论 Reference */
    demo.gp.review.Review review = 5; /* 评论 */
    bool is_deprecated = 6; /* Is Deprecated */
    int32 version = 7; /* Version */
    int32 realm_id = 8; /* Realm ID */
    string create_user_id = 9; /* Create User ID */
    google.protobuf.Timestamp create_time = 10; /* Create Time */
    string update_user_id = 11; /* Update User ID */
    google.protobuf.Timestamp update_time = 12; /* Update Time */
    string create_group_id = 13; /* Create Group ID */
    string intro_typename = 14; /* Type Name */
    int32 id_count = 15; /* Count of Relationship Object between 产品 and 评论 */
    int32 id_max = 16; /* Max of ID */
    int32 id_min = 17; /* Min of ID */
    int32 product_ref_count = 18; /* Count of 产品 Reference */
    string product_ref_max = 19; /* Max of 产品 Reference */
    string product_ref_min = 20; /* Min of 产品 Reference */
    int32 review_ref_count = 21; /* Count of 评论 Reference */
    int32 review_ref_sum = 22; /* Sum of 评论 Reference */
    int32 review_ref_avg = 23; /* Avg of 评论 Reference */
    int32 review_ref_max = 24; /* Max of 评论 Reference */
    int32 review_ref_min = 25; /* Min of 评论 Reference */
}
/**
* Relationship Object between 订单 and 用户
*/
message OrderUserRelation {
    string id = 1; /* ID */
    string order_ref = 2; /* 订单 Reference */
    Order order = 3; /* 订单 */
    int32 user_ref = 4; /* 用户 Reference */
    demo.gp.user.User user = 5; /* 用户 */
    bool is_deprecated = 6; /* Is Deprecated */
    int32 version = 7; /* Version */
    int32 realm_id = 8; /* Realm ID */
    string create_user_id = 9; /* Create User ID */
    google.protobuf.Timestamp create_time = 10; /* Create Time */
    string update_user_id = 11; /* Update User ID */
    google.protobuf.Timestamp update_time = 12; /* Update Time */
    string create_group_id = 13; /* Create Group ID */
    string intro_typename = 14; /* Type Name */
    int32 id_count = 15; /* Count of Relationship Object between 订单 and 用户 */
    int32 id_max = 16; /* Max of ID */
    int32 id_min = 17; /* Min of ID */
    int32 order_ref_count = 18; /* Count of 订单 Reference */
    string order_ref_max = 19; /* Max of 订单 Reference */
    string order_ref_min = 20; /* Min of 订单 Reference */
    int32 user_ref_count = 21; /* Count of 用户 Reference */
    int32 user_ref_sum = 22; /* Sum of 用户 Reference */
    int32 user_ref_avg = 23; /* Avg of 用户 Reference */
    int32 user_ref_max = 24; /* Max of 用户 Reference */
    int32 user_ref_min = 25; /* Min of 用户 Reference */
}
/**
* Connection Object for 产品
*/
message ProductConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated ProductEdge edges = 3; /* Edges */
}
/**
* Edge Object for 产品
*/
message ProductEdge {
    Product node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for 订单
*/
message OrderConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated OrderEdge edges = 3; /* Edges */
}
/**
* Edge Object for 订单
*/
message OrderEdge {
    Order node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for 订单项
*/
message OrderItemConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated OrderItemEdge edges = 3; /* Edges */
}
/**
* Edge Object for 订单项
*/
message OrderItemEdge {
    OrderItem node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for Relationship Object between 订单 and 订单项
*/
message OrderOrderItemRelationConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated OrderOrderItemRelationEdge edges = 3; /* Edges */
}
/**
* Edge Object for Relationship Object between 订单 and 订单项
*/
message OrderOrderItemRelationEdge {
    OrderOrderItemRelation node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for Relationship Object between 订单项 and 产品
*/
message OrderItemProductRelationConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated OrderItemProductRelationEdge edges = 3; /* Edges */
}
/**
* Edge Object for Relationship Object between 订单项 and 产品
*/
message OrderItemProductRelationEdge {
    OrderItemProductRelation node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for Relationship Object between 产品 and 评论
*/
message ProductReviewRelationConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated ProductReviewRelationEdge edges = 3; /* Edges */
}
/**
* Edge Object for Relationship Object between 产品 and 评论
*/
message ProductReviewRelationEdge {
    ProductReviewRelation node = 1; /* Node */
    string cursor = 2; /* Cursor */
}
/**
* Connection Object for Relationship Object between 订单 and 用户
*/
message OrderUserRelationConnection {
    int32 total_count = 1; /* Total */
    io.graphoenix.core.PageInfo page_info = 2; /* Page Info */
    repeated OrderUserRelationEdge edges = 3; /* Edges */
}
/**
* Edge Object for Relationship Object between 订单 and 用户
*/
message OrderUserRelationEdge {
    OrderUserRelation node = 1; /* Node */
    string cursor = 2; /* Cursor */
}