syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.user.grpc";

package demo.gp.user;

import "demo/gp/user/enums.proto";
import "demo/gp/user/objects.proto";
import "demo/gp/user/interfaces.proto";
import "demo/gp/user/input_objects.proto";
import "google/protobuf/timestamp.proto";

message MutationUserRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* 用户ID */
    string name = 4; /* 用户名 */
    string email = 5; /* 电子邮箱 */
    repeated string phone_numbers = 6; /* 联系方式 */
    UserType user_type = 7; /* 用户类型 */
    bool is_deprecated = 8; /* Is Deprecated */
    int32 version = 9; /* Version */
    int32 realm_id = 10; /* Realm ID */
    string create_user_id = 11; /* Create User ID */
    google.protobuf.Timestamp create_time = 12; /* Create Time */
    string update_user_id = 13; /* Update User ID */
    google.protobuf.Timestamp update_time = 14; /* Update Time */
    string create_group_id = 15; /* Create Group ID */
    string intro_typename = 16; /* Type Name */
    repeated UserPhoneNumbersRelationInput user_phone_numbers_relation = 17; /* Relationship Object between 用户 and 联系方式 */
    UserInput input = 18; /* Input */
    UserExpression where = 19; /* Where */
}
message MutationUserListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* 用户ID */
    string name = 4; /* 用户名 */
    string email = 5; /* 电子邮箱 */
    repeated string phone_numbers = 6; /* 联系方式 */
    UserType user_type = 7; /* 用户类型 */
    bool is_deprecated = 8; /* Is Deprecated */
    int32 version = 9; /* Version */
    int32 realm_id = 10; /* Realm ID */
    string create_user_id = 11; /* Create User ID */
    google.protobuf.Timestamp create_time = 12; /* Create Time */
    string update_user_id = 13; /* Update User ID */
    google.protobuf.Timestamp update_time = 14; /* Update Time */
    string create_group_id = 15; /* Create Group ID */
    string intro_typename = 16; /* Type Name */
    repeated UserPhoneNumbersRelationInput user_phone_numbers_relation = 17; /* Relationship Object between 用户 and 联系方式 */
    repeated UserInput list = 18; /* Input List */
    UserExpression where = 19; /* Where */
}
message MutationUserPhoneNumbersRelationRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* ID */
    string user_ref = 4; /* 用户 Reference */
    UserInput user = 5; /* 用户 */
    string phone_numbers_ref = 6; /* 联系方式 Reference */
    bool is_deprecated = 7; /* Is Deprecated */
    int32 version = 8; /* Version */
    int32 realm_id = 9; /* Realm ID */
    string create_user_id = 10; /* Create User ID */
    google.protobuf.Timestamp create_time = 11; /* Create Time */
    string update_user_id = 12; /* Update User ID */
    google.protobuf.Timestamp update_time = 13; /* Update Time */
    string create_group_id = 14; /* Create Group ID */
    string intro_typename = 15; /* Type Name */
    UserPhoneNumbersRelationInput input = 16; /* Input */
    UserPhoneNumbersRelationExpression where = 17; /* Where */
}
message MutationUserPhoneNumbersRelationListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* ID */
    string user_ref = 4; /* 用户 Reference */
    UserInput user = 5; /* 用户 */
    string phone_numbers_ref = 6; /* 联系方式 Reference */
    bool is_deprecated = 7; /* Is Deprecated */
    int32 version = 8; /* Version */
    int32 realm_id = 9; /* Realm ID */
    string create_user_id = 10; /* Create User ID */
    google.protobuf.Timestamp create_time = 11; /* Create Time */
    string update_user_id = 12; /* Update User ID */
    google.protobuf.Timestamp update_time = 13; /* Update Time */
    string create_group_id = 14; /* Create Group ID */
    string intro_typename = 15; /* Type Name */
    repeated UserPhoneNumbersRelationInput list = 16; /* Input List */
    UserPhoneNumbersRelationExpression where = 17; /* Where */
}