syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.user.grpc";

package demo.gp.user;

import "demo/gp/user/enums.proto";
import "demo/gp/user/objects.proto";
import "demo/gp/user/interfaces.proto";
import "demo/gp/user/input_objects.proto";
import "demo/gp/user/mutation_requests.proto";
import "demo/gp/user/mutation_responses.proto";

/**
* Mutation
*/
service MutationService {
    rpc User (MutationUserRequest) returns (MutationUserResponse); /* Mutation Field for 用户 */
    rpc UserList (MutationUserListRequest) returns (MutationUserListResponse); /* Mutation Field for 用户 List */
    rpc UserPhoneNumbersRelation (MutationUserPhoneNumbersRelationRequest) returns (MutationUserPhoneNumbersRelationResponse); /* Mutation Field for Relationship Object between 用户 and 联系方式 */
    rpc UserPhoneNumbersRelationList (MutationUserPhoneNumbersRelationListRequest) returns (MutationUserPhoneNumbersRelationListResponse); /* Mutation Field for Relationship Object between 用户 and 联系方式 List */
}