syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.user.grpc";

package demo.gp.user;

import "demo/gp/user/enums.proto";
import "demo/gp/user/objects.proto";
import "demo/gp/user/interfaces.proto";
import "demo/gp/user/input_objects.proto";
import "io/graphoenix/core/enums.proto";
import "io/graphoenix/core/input_objects.proto";

message QueryUserRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 用户ID */
    io.graphoenix.core.StringExpression name = 4; /* 用户名 */
    io.graphoenix.core.StringExpression email = 5; /* 电子邮箱 */
    io.graphoenix.core.StringExpression phone_numbers = 6; /* 联系方式 */
    UserTypeExpression user_type = 7; /* 用户类型 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    UserPhoneNumbersRelationExpression user_phone_numbers_relation = 17; /* Relationship Object between 用户 and 联系方式 */
    repeated string group_by = 18; /* Group By */
    bool not = 19; /* Not */
    io.graphoenix.core.Conditional cond = 20; /* Condition */
    repeated UserExpression exs = 21; /* Expressions */
}
message QueryUserListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 用户ID */
    io.graphoenix.core.StringExpression name = 4; /* 用户名 */
    io.graphoenix.core.StringExpression email = 5; /* 电子邮箱 */
    io.graphoenix.core.StringExpression phone_numbers = 6; /* 联系方式 */
    UserTypeExpression user_type = 7; /* 用户类型 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    UserPhoneNumbersRelationExpression user_phone_numbers_relation = 17; /* Relationship Object between 用户 and 联系方式 */
    UserOrderBy order_by = 18; /* Order By */
    repeated string group_by = 19; /* Group By */
    bool not = 20; /* Not */
    io.graphoenix.core.Conditional cond = 21; /* Condition */
    repeated UserExpression exs = 22; /* Expressions */
    int32 first = 23; /* First */
    int32 last = 24; /* Last */
    int32 offset = 25; /* Offset */
    string after = 26; /* After */
    string before = 27; /* Before */
}
message QueryUserConnectionRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 用户ID */
    io.graphoenix.core.StringExpression name = 4; /* 用户名 */
    io.graphoenix.core.StringExpression email = 5; /* 电子邮箱 */
    io.graphoenix.core.StringExpression phone_numbers = 6; /* 联系方式 */
    UserTypeExpression user_type = 7; /* 用户类型 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    UserPhoneNumbersRelationExpression user_phone_numbers_relation = 17; /* Relationship Object between 用户 and 联系方式 */
    UserOrderBy order_by = 18; /* Order By */
    repeated string group_by = 19; /* Group By */
    bool not = 20; /* Not */
    io.graphoenix.core.Conditional cond = 21; /* Condition */
    repeated UserExpression exs = 22; /* Expressions */
    int32 first = 23; /* First */
    int32 last = 24; /* Last */
    int32 offset = 25; /* Offset */
    string after = 26; /* After */
    string before = 27; /* Before */
}
message QueryUserPhoneNumbersRelationRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression user_ref = 4; /* 用户 Reference */
    UserExpression user = 5; /* 用户 */
    io.graphoenix.core.StringExpression phone_numbers_ref = 6; /* 联系方式 Reference */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    repeated string group_by = 16; /* Group By */
    bool not = 17; /* Not */
    io.graphoenix.core.Conditional cond = 18; /* Condition */
    repeated UserPhoneNumbersRelationExpression exs = 19; /* Expressions */
}
message QueryUserPhoneNumbersRelationListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression user_ref = 4; /* 用户 Reference */
    UserExpression user = 5; /* 用户 */
    io.graphoenix.core.StringExpression phone_numbers_ref = 6; /* 联系方式 Reference */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    UserPhoneNumbersRelationOrderBy order_by = 16; /* Order By */
    repeated string group_by = 17; /* Group By */
    bool not = 18; /* Not */
    io.graphoenix.core.Conditional cond = 19; /* Condition */
    repeated UserPhoneNumbersRelationExpression exs = 20; /* Expressions */
    int32 first = 21; /* First */
    int32 last = 22; /* Last */
    int32 offset = 23; /* Offset */
    string after = 24; /* After */
    string before = 25; /* Before */
}
message QueryUserPhoneNumbersRelationConnectionRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression user_ref = 4; /* 用户 Reference */
    UserExpression user = 5; /* 用户 */
    io.graphoenix.core.StringExpression phone_numbers_ref = 6; /* 联系方式 Reference */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    UserPhoneNumbersRelationOrderBy order_by = 16; /* Order By */
    repeated string group_by = 17; /* Group By */
    bool not = 18; /* Not */
    io.graphoenix.core.Conditional cond = 19; /* Condition */
    repeated UserPhoneNumbersRelationExpression exs = 20; /* Expressions */
    int32 first = 21; /* First */
    int32 last = 22; /* Last */
    int32 offset = 23; /* Offset */
    string after = 24; /* After */
    string before = 25; /* Before */
}