plugins {
    id 'java'
}

group 'demo.gp.order'
version '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation platform('org.graphoenix:graphoenix-platform:0.1.0-SNAPSHOT')

    implementation project(':user-package')
    implementation project(':review-package')
    implementation project(':order-package')
    implementation 'org.graphoenix:graphoenix-core'
    implementation 'org.graphoenix:graphoenix-r2dbc'
    implementation 'org.graphoenix:graphoenix-http-server'
    implementation 'org.graphoenix:graphoenix-grpc-server'
    implementation 'org.graphoenix:graphoenix-grpc-client'
    implementation 'org.graphoenix:graphoenix-gossip'
    implementation 'org.graphoenix:graphoenix-introspection'
    implementation 'org.graphoenix:graphoenix-admin'
    implementation 'org.graphoenix:nozdormu-inject'
    implementation 'org.graphoenix:nozdormu-async'
    implementation 'org.graphoenix:nozdormu-interceptor'
    implementation 'org.graphoenix:nozdormu-config'
    // osx required
    implementation group: 'io.netty', name: 'netty-resolver-dns-native-macos', version: '4.1.75.Final', classifier: 'osx-aarch_64'

    runtimeOnly 'org.mariadb:r2dbc-mariadb:1.1.4'

    annotationProcessor project(':order-package')
    annotationProcessor 'org.graphoenix:graphoenix-annotation-processor'
    annotationProcessor 'org.graphoenix:graphoenix-sql'
    annotationProcessor 'org.graphoenix:graphoenix-grpc-server'
    annotationProcessor 'org.graphoenix:graphoenix-grpc-client'
    annotationProcessor 'org.graphoenix:graphoenix-introspection'
    annotationProcessor 'org.graphoenix:graphoenix-gossip'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'io.projectreactor:reactor-test'
    testRuntimeOnly 'io.projectreactor:reactor-test'
}

test {
    useJUnitPlatform()
    exclude '**/test/grpc/**'
}