syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.review.grpc";

package demo.gp.review;

import "demo/gp/review/enums.proto";
import "demo/gp/review/objects.proto";
import "demo/gp/review/interfaces.proto";
import "demo/gp/review/input_objects.proto";
import "demo/gp/user/input_objects.proto";
import "google/protobuf/timestamp.proto";

message MutationReviewRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* 评论ID */
    string content = 4; /* 评论内容 */
    float rating = 5; /* 评分 */
    demo.gp.user.UserInput user = 6; /* 评论人 */
    bool is_deprecated = 7; /* Is Deprecated */
    int32 version = 8; /* Version */
    int32 realm_id = 9; /* Realm ID */
    string create_user_id = 10; /* Create User ID */
    google.protobuf.Timestamp create_time = 11; /* Create Time */
    string update_user_id = 12; /* Update User ID */
    google.protobuf.Timestamp update_time = 13; /* Update Time */
    string create_group_id = 14; /* Create Group ID */
    string intro_typename = 15; /* Type Name */
    repeated ReviewUserRelationInput review_user_relation = 16; /* Relationship Object between 评论 and 用户 */
    ReviewInput input = 17; /* Input */
    ReviewExpression where = 18; /* Where */
}
message MutationReviewListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* 评论ID */
    string content = 4; /* 评论内容 */
    float rating = 5; /* 评分 */
    demo.gp.user.UserInput user = 6; /* 评论人 */
    bool is_deprecated = 7; /* Is Deprecated */
    int32 version = 8; /* Version */
    int32 realm_id = 9; /* Realm ID */
    string create_user_id = 10; /* Create User ID */
    google.protobuf.Timestamp create_time = 11; /* Create Time */
    string update_user_id = 12; /* Update User ID */
    google.protobuf.Timestamp update_time = 13; /* Update Time */
    string create_group_id = 14; /* Create Group ID */
    string intro_typename = 15; /* Type Name */
    repeated ReviewUserRelationInput review_user_relation = 16; /* Relationship Object between 评论 and 用户 */
    repeated ReviewInput list = 17; /* Input List */
    ReviewExpression where = 18; /* Where */
}
message MutationReviewUserRelationRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* ID */
    string review_ref = 4; /* 评论 Reference */
    ReviewInput review = 5; /* 评论 */
    int32 user_ref = 6; /* 用户 Reference */
    demo.gp.user.UserInput user = 7; /* 用户 */
    bool is_deprecated = 8; /* Is Deprecated */
    int32 version = 9; /* Version */
    int32 realm_id = 10; /* Realm ID */
    string create_user_id = 11; /* Create User ID */
    google.protobuf.Timestamp create_time = 12; /* Create Time */
    string update_user_id = 13; /* Update User ID */
    google.protobuf.Timestamp update_time = 14; /* Update Time */
    string create_group_id = 15; /* Create Group ID */
    string intro_typename = 16; /* Type Name */
    ReviewUserRelationInput input = 17; /* Input */
    ReviewUserRelationExpression where = 18; /* Where */
}
message MutationReviewUserRelationListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    string id = 3; /* ID */
    string review_ref = 4; /* 评论 Reference */
    ReviewInput review = 5; /* 评论 */
    int32 user_ref = 6; /* 用户 Reference */
    demo.gp.user.UserInput user = 7; /* 用户 */
    bool is_deprecated = 8; /* Is Deprecated */
    int32 version = 9; /* Version */
    int32 realm_id = 10; /* Realm ID */
    string create_user_id = 11; /* Create User ID */
    google.protobuf.Timestamp create_time = 12; /* Create Time */
    string update_user_id = 13; /* Update User ID */
    google.protobuf.Timestamp update_time = 14; /* Update Time */
    string create_group_id = 15; /* Create Group ID */
    string intro_typename = 16; /* Type Name */
    repeated ReviewUserRelationInput list = 17; /* Input List */
    ReviewUserRelationExpression where = 18; /* Where */
}