syntax = "proto3";

option java_multiple_files = true;
option java_package = "demo.gp.review.grpc";

package demo.gp.review;

import "demo/gp/review/enums.proto";
import "demo/gp/review/objects.proto";
import "demo/gp/review/interfaces.proto";
import "demo/gp/review/input_objects.proto";
import "io/graphoenix/core/enums.proto";
import "io/graphoenix/core/input_objects.proto";
import "demo/gp/user/input_objects.proto";

message QueryReviewRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 评论ID */
    io.graphoenix.core.StringExpression content = 4; /* 评论内容 */
    io.graphoenix.core.FloatExpression rating = 5; /* 评分 */
    demo.gp.user.UserExpression user = 6; /* 评论人 */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    ReviewUserRelationExpression review_user_relation = 16; /* Relationship Object between 评论 and 用户 */
    repeated string group_by = 17; /* Group By */
    bool not = 18; /* Not */
    io.graphoenix.core.Conditional cond = 19; /* Condition */
    repeated ReviewExpression exs = 20; /* Expressions */
}
message QueryReviewListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 评论ID */
    io.graphoenix.core.StringExpression content = 4; /* 评论内容 */
    io.graphoenix.core.FloatExpression rating = 5; /* 评分 */
    demo.gp.user.UserExpression user = 6; /* 评论人 */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    ReviewUserRelationExpression review_user_relation = 16; /* Relationship Object between 评论 and 用户 */
    ReviewOrderBy order_by = 17; /* Order By */
    repeated string group_by = 18; /* Group By */
    bool not = 19; /* Not */
    io.graphoenix.core.Conditional cond = 20; /* Condition */
    repeated ReviewExpression exs = 21; /* Expressions */
    int32 first = 22; /* First */
    int32 last = 23; /* Last */
    int32 offset = 24; /* Offset */
    string after = 25; /* After */
    string before = 26; /* Before */
}
message QueryReviewConnectionRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* 评论ID */
    io.graphoenix.core.StringExpression content = 4; /* 评论内容 */
    io.graphoenix.core.FloatExpression rating = 5; /* 评分 */
    demo.gp.user.UserExpression user = 6; /* 评论人 */
    bool include_deprecated = 7; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 8; /* Version */
    io.graphoenix.core.IntExpression realm_id = 9; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 10; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 11; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 12; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 13; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 14; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 15; /* Type Name */
    ReviewUserRelationExpression review_user_relation = 16; /* Relationship Object between 评论 and 用户 */
    ReviewOrderBy order_by = 17; /* Order By */
    repeated string group_by = 18; /* Group By */
    bool not = 19; /* Not */
    io.graphoenix.core.Conditional cond = 20; /* Condition */
    repeated ReviewExpression exs = 21; /* Expressions */
    int32 first = 22; /* First */
    int32 last = 23; /* Last */
    int32 offset = 24; /* Offset */
    string after = 25; /* After */
    string before = 26; /* Before */
}
message QueryReviewUserRelationRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression review_ref = 4; /* 评论 Reference */
    ReviewExpression review = 5; /* 评论 */
    io.graphoenix.core.IntExpression user_ref = 6; /* 用户 Reference */
    demo.gp.user.UserExpression user = 7; /* 用户 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    repeated string group_by = 17; /* Group By */
    bool not = 18; /* Not */
    io.graphoenix.core.Conditional cond = 19; /* Condition */
    repeated ReviewUserRelationExpression exs = 20; /* Expressions */
}
message QueryReviewUserRelationListRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression review_ref = 4; /* 评论 Reference */
    ReviewExpression review = 5; /* 评论 */
    io.graphoenix.core.IntExpression user_ref = 6; /* 用户 Reference */
    demo.gp.user.UserExpression user = 7; /* 用户 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    ReviewUserRelationOrderBy order_by = 17; /* Order By */
    repeated string group_by = 18; /* Group By */
    bool not = 19; /* Not */
    io.graphoenix.core.Conditional cond = 20; /* Condition */
    repeated ReviewUserRelationExpression exs = 21; /* Expressions */
    int32 first = 22; /* First */
    int32 last = 23; /* Last */
    int32 offset = 24; /* Offset */
    string after = 25; /* After */
    string before = 26; /* Before */
}
message QueryReviewUserRelationConnectionRequest {
    optional string selection_set = 1;
    optional string arguments = 2;
    io.graphoenix.core.StringExpression id = 3; /* ID */
    io.graphoenix.core.StringExpression review_ref = 4; /* 评论 Reference */
    ReviewExpression review = 5; /* 评论 */
    io.graphoenix.core.IntExpression user_ref = 6; /* 用户 Reference */
    demo.gp.user.UserExpression user = 7; /* 用户 */
    bool include_deprecated = 8; /* Include Deprecated */
    io.graphoenix.core.IntExpression version = 9; /* Version */
    io.graphoenix.core.IntExpression realm_id = 10; /* Realm ID */
    io.graphoenix.core.StringExpression create_user_id = 11; /* Create User ID */
    io.graphoenix.core.StringExpression create_time = 12; /* Create Time */
    io.graphoenix.core.StringExpression update_user_id = 13; /* Update User ID */
    io.graphoenix.core.StringExpression update_time = 14; /* Update Time */
    io.graphoenix.core.StringExpression create_group_id = 15; /* Create Group ID */
    io.graphoenix.core.StringExpression intro_typename = 16; /* Type Name */
    ReviewUserRelationOrderBy order_by = 17; /* Order By */
    repeated string group_by = 18; /* Group By */
    bool not = 19; /* Not */
    io.graphoenix.core.Conditional cond = 20; /* Condition */
    repeated ReviewUserRelationExpression exs = 21; /* Expressions */
    int32 first = 22; /* First */
    int32 last = 23; /* Last */
    int32 offset = 24; /* Offset */
    string after = 25; /* After */
    string before = 26; /* Before */
}